import type { Metadata } from "next";
import { Fira_Sans } from "next/font/google";
import "./globals.css";
import Header from "../blocks/Header";
import background from "../assets/system-grid.svg"

const firaSans = Fira_Sans({
  weight: ["300", "400", "600"],
  subsets: ["latin"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${firaSans.className} antialiased`}
        style={{
          backgroundImage: `url(${background.src})`,
          backgroundRepeat: 'repeat',
          backgroundSize: '470px 470px',
          backgroundPosition: 'top',
        }}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
